const base=(title,body,script='')=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f6f7f1"><title>${title} · Bernardo Musiello</title><link rel="icon" href="/assets/favicon.svg"><link rel="stylesheet" href="/fonts.css"><link rel="stylesheet" href="/studio.css?v=11"></head><body>${body}${script?`<script type="module" src="${script}"></script>`:''}</body></html>`;
export const adminDocument=()=>base('Studio',`
<header class="studio-header"><a class="brand" href="/">b<span>.</span></a><span class="header-title">Portfolio studio <small>Private</small></span><nav><a href="/" target="_blank" rel="noopener">View portfolio ↗</a><a id="signout" href="/signout-with-chatgpt?return_to=%2Fadmin" target="_top" hidden>Sign out</a></nav></header>
<main id="gate" class="gate"><p class="eyebrow">YOUR LITTLE CORNER</p><h1>A home for your work.</h1><p id="gate-message">Checking your access…</p><a id="signin" class="button primary" href="/signin-with-chatgpt?return_to=%2Fadmin" target="_top" hidden>Sign in with ChatGPT</a></main>
<main id="studio" class="studio" hidden>
<aside class="library"><div class="library-top"><h1>Your projects</h1><button id="new-project" class="button primary">+ Add project</button></div><label class="search-label">Find a project<input id="project-search" type="search" placeholder="Search your work"></label><div class="library-tabs" role="group" aria-label="Project views"><button id="active-tab" aria-pressed="true">Projects</button><button id="trash-tab" aria-pressed="false">Trash</button></div><div id="project-list"></div><div class="library-bottom"><a href="/api/admin/export" download>Export project details ↓</a><p id="storage-used"></p><p>Backup export includes project details. Download your original files separately.</p><a href="/privacy">Privacy</a> · <a href="/credits">Copyright & credits</a></div></aside>
<section class="workspace"><div id="blank" class="blank"><img src="/assets/fern.png" alt="" width="120" height="120"><h2>Make room for something real.</h2><p>Add a website, a finished video, or anything you’ve made. It stays private until you publish it.</p><button id="first-project" class="button primary">Add your first project</button></div>
<form id="editor" hidden><div class="editor-top"><div><p class="eyebrow" id="project-state">DRAFT</p><h2 id="editor-title">New project</h2><p id="save-status" role="status">Only you can see this.</p></div><div class="editor-actions"><button type="button" id="preview-project" class="button">Preview</button><button type="submit" id="save-project" class="button">Save draft</button><button type="button" id="publish-project" class="button primary">Publish</button></div></div>
<div id="editor-fields"><div class="field-grid"><label class="span-2">Project title<input name="title" maxlength="100" required placeholder="Give your work a name"></label><label>Category<select name="kind"><option>Website</option><option>Video</option><option>Broadcast graphic</option><option>Product</option><option>App</option><option>Other</option></select></label><label>Year<input name="year" type="number" min="1900" max="2100" required></label><label class="span-2">Short introduction<textarea name="summary" maxlength="280" rows="2" placeholder="What did you make, and what makes it yours?"></textarea><small>Shown in the project preview. Up to 280 characters.</small></label><label class="span-2">The story<textarea name="description" maxlength="10000" rows="5" placeholder="Tell the story behind the work."></textarea></label><label>Your role<input name="role" maxlength="300" placeholder="Editing, design, development…"></label><label>Website or demo link<input name="url" type="url" placeholder="https://" maxlength="2000"></label></div>
<section class="media-section"><div class="section-top"><div><h3>Images & files</h3><p>Choose a cover, add a video, and bring your work to life.</p></div><label class="button upload-button">+ Upload files<input id="upload-files" type="file" multiple accept=".mp4,.m4v,.webm,.jpg,.jpeg,.png,.webp,.pdf,.vtt"></label></div><p class="field-hint">Videos up to 1 GB · JPG, PNG, WebP up to 20 MB · PDF up to 25 MB · VTT captions up to 2 MB</p><div id="upload-queue" aria-live="polite"></div><div id="media-grid" class="media-grid"></div><p id="media-empty" class="empty-media">Your files will appear here. Save this draft to start uploading.</p><label>Cover image description<input name="imageAlt" maxlength="300" placeholder="Describe the cover for someone who can’t see it."></label></section>
<details class="editor-details"><summary>Video accessibility</summary><p>Upload a .vtt file to add captions, or include a text version of the video below.</p><label>Transcript<textarea name="transcript" rows="6" maxlength="16000" placeholder="Spoken words and important visual context…"></textarea></label></details>
<label class="credits-field">Collaborators & credits<textarea name="credits" rows="3" maxlength="2000" placeholder="Credit the people, music, footage, or other material used with permission."></textarea></label>
<div class="project-tools"><button type="button" id="unpublish-project" class="text-button" hidden>Unpublish</button><button type="button" id="trash-project" class="text-button danger">Move to trash</button><button type="button" id="restore-project" class="button" hidden>Restore draft</button><button type="button" id="delete-project" class="text-button danger" hidden>Delete permanently</button></div></div></form>
</section></main>
<div id="toast" role="status" aria-live="polite" hidden></div>
<dialog id="confirm-dialog"><form method="dialog"><h2 id="confirm-title"></h2><p id="confirm-description"></p><label id="rights-label" class="check-label" hidden><input type="checkbox" id="rights-confirmed">I have permission to publish this work, including its music, images, footage and any people or client material shown.</label><p id="rights-note" class="field-hint" hidden>Credits do not replace permission. Keep your original files and any licenses or releases.</p><div class="dialog-actions"><button class="button" value="cancel">Cancel</button><button id="confirm-yes" class="button primary" value="confirm">Continue</button></div></form></dialog>
<dialog id="preview-dialog" class="preview-dialog"><button type="button" class="close-preview" aria-label="Close project preview">×</button><p class="eyebrow">PRIVATE PREVIEW</p><div id="preview-content"></div></dialog>
`, '/studio.js?v=11');
const noticeHeader=`<header class="studio-header"><a class="brand" href="/">b<span>.</span></a><a href="/">Back to the portfolio</a></header>`;
export function noticeDocument(kind){return base(kind==='privacy'?'Privacy':'Copyright & credits',noticeHeader+`<main class="notice">${kind==='privacy'?`
<p class="eyebrow">LAST UPDATED SEPTEMBER 16, 2026</p><h1>Privacy</h1><p>This is Bernardo Musiello’s personal portfolio. For a privacy question, contact <a href="mailto:bernardomusiello@gmail.com">bernardomusiello@gmail.com</a>.</p>
<h2>Visiting the portfolio</h2><p>This application does not add advertising trackers, analytics, public accounts, or a contact form. It is hosted through OpenAI Sites on Cloudflare infrastructure. Hosting and security services may process request information such as IP addresses, browser details and access logs to deliver and protect the site. Their handling and retention of service data are governed by their own policies.</p>
<h2>Private studio and project files</h2><p>The studio uses ChatGPT sign-in. The server receives an account identifier and email address to recognize the authorized owner. Only that owner can edit projects or access unpublished files. Project details and uploaded media are stored with the hosting services. Saving a draft does not publish it. Published projects and the files attached to them can be viewed by the audience allowed to access this portfolio.</p><p>Drafts and trashed projects are retained until the owner removes them. A trash action is reversible and unpublishes the project. Files can be permanently removed from the media library when they are no longer attached to a draft or published version. Unpublishing cannot remove copies someone already downloaded.</p>
<h2>Sign-in and browser storage</h2><p>The hosting platform manages sign-in cookies. The application does not set marketing cookies. Its editor uses temporary browser memory for unsaved edits and upload progress; saved projects and upload-part records are stored on the server.</p>
<h2>Links, email and AI tools</h2><p>Instagram, LinkedIn, GitHub and other project links take you to separate services. Email opens your mail application. The “Ask an AI” menu shows a prepared portfolio prompt and opens your chosen AI service only when you choose it. That service receives the prompt in the link and applies its own privacy policy. The portfolio does not send private drafts or uploaded originals in that prompt.</p>
<h2>Your questions</h2><p>If you appear in a published project or have a privacy or rights concern, email the page link and enough detail to identify the material. Avoid sending sensitive documents unless they are needed to resolve your request.</p>
<p class="notice-links"><a href="https://openai.com/policies/privacy-policy/" target="_blank" rel="noopener noreferrer">OpenAI privacy policy ↗</a><a href="https://www.cloudflare.com/privacypolicy/" target="_blank" rel="noopener noreferrer">Cloudflare privacy policy ↗</a></p>`:`
<p class="eyebrow">A NOTE ABOUT THE WORK</p><h1>Copyright & credits</h1><p>Portfolio projects may include work by Bernardo Musiello and credited collaborators or third parties. Displaying work here does not grant a license to reuse the project’s images, videos, music, text or other creative materials. Contact <a href="mailto:bernardomusiello@gmail.com">bernardomusiello@gmail.com</a> for permission or a rights concern.</p>
<h2>The website’s source code</h2><p>The portfolio’s open-source code is available under the MIT license in its <a href="https://github.com/bernardopmusiello-droid/bernardo-portfolio" target="_blank" rel="noopener noreferrer">GitHub repository</a>. That code license does not automatically apply to projects uploaded through the studio. Third-party assets retain their own licenses.</p>
<h2>Design and artwork</h2><p>The layout was adapted from Aditya Ojha’s MIT-licensed portfolio. Its license notice is preserved with the source. The nature and space illustrations were generated with AI. Font, icon and illustration details are recorded in the <a href="/THIRD_PARTY_NOTICES.md">third-party notices</a> and the repository’s artwork manifest.</p>
<h2>Publishing responsibly</h2><p>Project credits identify collaborators and licensed material where supplied. Credit alone does not replace permission. Music, footage, photographs, logos and client work may have separate permissions or restrictions. If you believe a project uses your work or personal information improperly, please send its page link and a description of the concern.</p>`}</main>`);}
